### ISSUE TITLE
Which version of VirtualBox to use? PC and Linux hardcoded to 4.3.3, Mac installs latest via Brew

### ISSUE THREAD

**Issue by alexkogon** [bbaassssiiee/buildserver#18]
I'm not sure if the version of VirtualBox is important, but the PC and Linux instructions in the README have a link to an older version, while the Mac will install the latest via the brew instructions

**Comment by bbaassssiiee** [comment]
Not that important, but 4.3.30 guest additions are in dockpack/centos6

On 24 Aug 2015, at 10:51, Alex Kogon <notifications@github.com> wrote:

I'm not sure if the version of VirtualBox is important, but the PC and Linux instructions in the README have a link to an older version, while the Mac will install the latest via the brew instructions

**Comment by alexkogon** [comment]
ok, well hopefully both just work :) maybe we should make a note of that somewhere though, if the pc and linux users can use the latest version there may be other reasons that is helpful

**Comment by alexkogon** [comment]
I did see this error in the output but don't know if it is important:

==> target: Checking for guest additions in VM...
    target: The guest additions on this VM do not match the installed version of
    target: VirtualBox! In most cases this is fine, but in rare cases it can
    target: prevent things such as shared folders from working properly. If you see
    target: shared folder errors, please make sure the guest additions within the
    target: virtual machine match the version of VirtualBox you have installed on
    target: your host and reload your VM.
    target:
    target: Guest Additions Version: 4.3.30
    target: VirtualBox Version: 5.0

**Comment by bbaassssiiee** [comment]
Not important, we don't use guest additions (yet). I can update the image.



On 24 Aug 2015, at 11:08, Alex Kogon <notifications@github.com> wrote:

I did see this error in the output but don't know if it is important:

==> target: Checking for guest additions in VM...
target: The guest additions on this VM do not match the installed version of
target: VirtualBox! In most cases this is fine, but in rare cases it can
target: prevent things such as shared folders from working properly. If you see
target: shared folder errors, please make sure the guest additions within the
target: virtual machine match the version of VirtualBox you have installed on
target: your host and reload your VM.
target:
target: Guest Additions Version: 4.3.30
target: VirtualBox Version: 5.0
