### ISSUE TITLE
Error at ansible provisioning 

### ISSUE THREAD

**Issue by sraesmit** [bbaassssiiee/buildserver#24]
at "ansible-playbook -l build:target provision.yml" 
I'm getting an error back "expect is not a legal parameter in Ansible task. I updated to the latest Ansible via brew. Thoughts?  -Tim

Also - this is a great repo. I'm looking to do something simlar except with a RHEL6.7 STIG box as a vagrant cluster.

**Comment by bbaassssiiee** [comment]
Ansible 2.1 comes with the "expect" module. 
You can run on Centos 6 DISA-STIG if you run "ansible-playbook -l dev:target provision.yml". The dockpack/centos6 base image has already been hardened to DISA STIG (but a while ago).
