### ISSUE TITLE
minor issue on 'make install' regarding 

### ISSUE THREAD

**Issue by mkinney** [bbaassssiiee/buildserver#27]
I got this message when running 'make install'

==> target: Loading metadata for box 'https://atlas.hashicorp.com/centos/7'
    target: URL: https://atlas.hashicorp.com/centos/7
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: dockpack/centos6
Actual name: centos/7

To continue, I made this change:
+    #tartget_slave.vm.box = "dockpack/centos6"
+    tartget_slave.vm.box = "centos/7"

**Comment by bbaassssiiee** [comment]
Thanks, fixed.
