### ISSUE TITLE
error in 'make install'

### ISSUE THREAD

**Issue by mkinney** [bbaassssiiee/buildserver#28]
I got this error when running 'make install'

PLAY RECAP **************************************************************************************************************************
build_master               : ok=204  changed=125  unreachable=0    failed=0

**Install Docker on target too**
ansible-playbook -l target playbook.yml
ERROR! the playbook: playbook.yml could not be found
make: *** [install] Error 1

**Comment by Petrox** [comment]
Following the steps in readme.md:

````
buildserver$ make install
make: *** No rule to make target 'install'.  Stop.
````

````
buildserver$ make
Beginner tasks:
make setup         -install requirements and generate keys
make myself        -install on centos7
make vagrant       -Install two virtual machines only
make build         -Build the application game of life
make cleanroles    -Cleanup vm's and  ansible roles
````
