### ISSUE TITLE
'make install' issue - boxes dir does not exist

### ISSUE THREAD

**Issue by mkinney** [bbaassssiiee/buildserver#29]
Looks like the boxes dir does not exist so this fails:

**Bring up the windows 7 VM, and provision it:**
vagrant up --no-provision windows
The machine with the name 'windows' was not found configured for
this Vagrant environment.
make: *** [install] Error 1

This seems to run this:
	vagrant box add -f -name windows boxes/windows.box

But there is not boxes directory. Is there some target that needs to be run to create that dir? Or is that dir not added to repo?

**Comment by bbaassssiiee** [comment]
There is work in progress in the master branch, checkout v1.0 as released. The boxes can be found on atlas.hashicorp.com or modern.ie
